package yike

import (
	"net/http"
	"net/url"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// This vector is published in Alibaba Cloud's "V3 request structure and
// signature" documentation (RunInstances fixed-parameter example). Keeping it
// separate from the Yike vector prevents the implementation from testing only
// against an expectation generated by itself.
func TestV3SignerAlibabaCloudOfficialVector(t *testing.T) {
	endpoint, err := buildEndpoint("https://ecs.cn-shanghai.aliyuncs.com", url.Values{
		"ImageId":  {"win2019_1809_x64_dtc_zh-cn_40G_alibase_20230811.vhd"},
		"RegionId": {"cn-shanghai"},
	})
	require.NoError(t, err)
	req, err := http.NewRequest(http.MethodPost, endpoint, nil)
	require.NoError(t, err)

	signer := &v3Signer{
		now: func() time.Time {
			return time.Date(2023, 10, 26, 10, 22, 32, 0, time.UTC)
		},
		nonce: func() (string, error) {
			return "3156853299f313e23d1673dc12e1703d", nil
		},
	}
	require.NoError(t, signer.sign(req, "RunInstances", "2014-05-26", "YourAccessKeyId", "YourAccessKeySecret"))

	assert.Equal(t,
		"ACS3-HMAC-SHA256 Credential=YourAccessKeyId,SignedHeaders=host;x-acs-action;x-acs-content-sha256;x-acs-date;x-acs-signature-nonce;x-acs-version,Signature=06563a9e1b43f5dfe96b81484da74bceab24a1d853912eee15083a6f0f3283c0",
		req.Header.Get("Authorization"),
	)
}

func TestCanonicalQueryUsesAlibabaPercentEncoding(t *testing.T) {
	query := url.Values{"value": {"space star* tilde~ plus+"}}

	assert.Equal(t, "value=space%20star%2A%20tilde~%20plus%2B", canonicalQuery(query))
}
