export default defineAppConfig({
  pages: [
    'pages/home/index',
    'pages/models/index',
    'pages/playground/index',
    'pages/usage/index',
    'pages/profile/index',
    'pages/media-preview/index',
    'pages/legal/index',
    'pages/model-detail/index',
    'pages/keys/index',
    'pages/billing-detail/index',
    'pages/wallet/index',
    'pages/account/index',
    'pages/sessions/index',
    'pages/benefits/index',
    'pages/privacy/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#f7f8fc',
    navigationBarTitleText: 'Home',
    navigationBarTextStyle: 'black',
  },
  tabBar: {
    color: '#687086',
    selectedColor: '#4f46e5',
    backgroundColor: '#ffffff',
    borderStyle: 'white',
    list: [
      { pagePath: 'pages/home/index', text: 'Home', iconPath: 'assets/tabbar/home.png', selectedIconPath: 'assets/tabbar/home-selected.png' },
      { pagePath: 'pages/models/index', text: 'Models', iconPath: 'assets/tabbar/models.png', selectedIconPath: 'assets/tabbar/models-selected.png' },
      { pagePath: 'pages/playground/index', text: 'Playground', iconPath: 'assets/tabbar/chat.png', selectedIconPath: 'assets/tabbar/chat-selected.png' },
      { pagePath: 'pages/usage/index', text: 'Usage', iconPath: 'assets/tabbar/usage.png', selectedIconPath: 'assets/tabbar/usage-selected.png' },
      { pagePath: 'pages/profile/index', text: 'Profile', iconPath: 'assets/tabbar/profile.png', selectedIconPath: 'assets/tabbar/profile-selected.png' },
    ],
  },
})
