/*
Copyright (C) 2023-2026 QuantumNous

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, please contact support@quantumnous.com
*/
import { expect, test } from 'vitest'

import {
  buildHtmlReport,
  buildVideoHtmlReport,
  type ReportInput,
  type VideoReportInput,
} from '../report'

test('supplier PDF omits address and timestamp metadata while keeping test results', () => {
  const input: ReportInput = {
    baseUrl: 'http://192.0.2.44/v1',
    model: 'demo-model',
    basicChecks: [{ id: 'connectivity', title: 'Connectivity', status: 'pass' }],
    cacheChecks: [],
    summaries: { basic: '', cache: '', stress: '' },
    stressAssessment: null,
    cacheAssessment: null,
    errorMessage: '',
    standardLabel: 'Default standard',
    statusLabel: (status) => status,
    t: (key) => key,
  }

  const pdfHtml = buildHtmlReport(input, { format: 'pdf' })
  const exportHtml = buildHtmlReport(input)

  expect(pdfHtml).toContain('<title>Supplier Test Report</title>')
  expect(pdfHtml).toContain('demo-model')
  expect(pdfHtml).toContain('Connectivity')
  expect(pdfHtml).not.toContain('192.0.2.44')
  expect(pdfHtml).not.toContain('Generated by Supplier Test')
  expect(pdfHtml).not.toContain('meta-label">Time')
  expect(exportHtml).toContain('http://192.0.2.44/v1')
  expect(exportHtml).toContain('Generated by Supplier Test')
})

test('video PDF omits upstream address and time while keeping task details', () => {
  const input: VideoReportInput = {
    baseUrl: 'http://192.0.2.44',
    endpointUrl: 'http://192.0.2.44/api/v3/contents/generations/tasks',
    model: 'demo-video-model',
    taskId: 'task-42',
    elapsedMs: 1800,
    videoConfig: {
      prompt: 'A sunset',
      hasImage: false,
      uploadMode: 'url',
      hasLastFrame: false,
    },
    videoChecks: [{ id: 'video_submit', title: 'Task submit', status: 'pass' }],
    t: (key) => key,
  }

  const pdfHtml = buildVideoHtmlReport(input, { format: 'pdf' })
  const exportHtml = buildVideoHtmlReport(input)

  expect(pdfHtml).toContain('<title>Doubao Video Generation Test Report</title>')
  expect(pdfHtml).toContain('demo-video-model')
  expect(pdfHtml).toContain('task-42')
  expect(pdfHtml).not.toContain('192.0.2.44')
  expect(pdfHtml).not.toContain('meta-label">Time')
  expect(exportHtml).toContain('http://192.0.2.44')
})
