/*
Copyright (C) 2023-2026 QuantumNous

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, please contact support@quantumnous.com
*/
import { expect, test, vi } from 'vitest'

import { api } from '@/lib/api'

import {
  buildHtmlReport,
  buildVideoHtmlReport,
  preparePdfBranding,
  type ReportInput,
  type VideoReportInput,
} from '../report'

test('PDF branding embeds the authenticated normalized operator logo', async () => {
  const branding = {
    platformName: 'Example Platform',
    platformLogo: '/logo.png',
    operatingEntityName: 'Example Operator Ltd',
    operatingEntityLogo: 'https://cdn.example/operator.png',
  }
  const get = vi.spyOn(api, 'get').mockResolvedValueOnce({
    data: new Blob(['image pixels'], { type: 'image/png' }),
  })
  try {
    const prepared = await preparePdfBranding(branding)
    expect(get).toHaveBeenCalledWith('/api/pdf-branding/operating-logo', {
      responseType: 'blob',
      skipErrorHandler: true,
    })
    expect(prepared?.operatingEntityLogo).toBe(
      'data:image/png;base64,aW1hZ2UgcGl4ZWxz'
    )
  } finally {
    get.mockRestore()
  }
})

test('supplier PDF omits address and timestamp metadata while keeping test results', () => {
  const input: ReportInput = {
    branding: {
      platformName: 'Example Platform',
      platformLogo: 'https://cdn.example/platform.png',
      operatingEntityName: 'Example Operator Ltd',
      operatingEntityLogo: 'https://cdn.example/operator.png',
    },
    baseUrl: 'http://192.0.2.44/v1',
    model: 'demo-model',
    basicChecks: [
      { id: 'connectivity', title: 'Connectivity', status: 'pass' },
    ],
    cacheChecks: [],
    summaries: { basic: '', cache: '', stress: '' },
    stressAssessment: null,
    cacheAssessment: null,
    errorMessage: '',
    standardLabel: 'Default standard',
    statusLabel: (status) => status,
    t: (key) => key,
  }

  const pdfHtml = buildHtmlReport(input, { format: 'pdf' })
  const exportHtml = buildHtmlReport(input)

  expect(pdfHtml).toMatch(/<title>Supplier Test\d{8}<\/title>/)
  expect(pdfHtml).toContain('demo-model')
  expect(pdfHtml).toContain('Connectivity')
  expect(pdfHtml).toContain('class="document-letterhead"')
  expect(pdfHtml).toContain('<table class="pdf-shell"><thead>')
  expect(pdfHtml).toContain('margin:33pt 40pt 58pt')
  expect(pdfHtml).toContain('.pdf-document .report-title { font-size:26pt')
  expect(pdfHtml).toContain('.document-summary-card { height:79pt')
  expect(pdfHtml).toContain('content:counter(page, decimal-leading-zero)')
  expect(pdfHtml).toContain('Example Platform')
  expect(pdfHtml).toContain('Example Operator Ltd')
  expect(pdfHtml).toContain(
    '<div class="document-operator"><img src="/api/pdf-branding/operating-logo" alt="Example Operator Ltd"/></div>'
  )
  expect(pdfHtml).toContain(
    '.document-operator img { width:125pt; height:40pt;'
  )
  expect(pdfHtml).not.toContain('<span>Example Operator Ltd</span>')
  expect(pdfHtml).toContain('192.0.2.44')
  expect(pdfHtml).not.toContain('Generated by Supplier Test')
  expect(pdfHtml).not.toContain('meta-label">Time')
  expect(exportHtml).toContain('http://192.0.2.44/v1')
  expect(exportHtml).toContain('Generated by Supplier Test')
  expect(exportHtml).not.toContain('class="document-letterhead"')

  const branding = input.branding
  if (!branding) throw new Error('missing test branding')
  const nameOnlyHtml = buildHtmlReport(
    {
      ...input,
      branding: { ...branding, operatingEntityLogo: '' },
    },
    { format: 'pdf' }
  )
  expect(nameOnlyHtml).toContain(
    '<div class="document-operator"><span>Example Operator Ltd</span></div>'
  )
})

test('video PDF omits upstream address and time while keeping task details', () => {
  const input: VideoReportInput = {
    branding: {
      platformName: 'Example Platform',
      platformLogo: 'https://cdn.example/platform.png',
      operatingEntityName: 'Example Operator Ltd',
      operatingEntityLogo: 'https://cdn.example/operator.png',
    },
    baseUrl: 'http://192.0.2.44',
    endpointUrl: 'http://192.0.2.44/api/v3/contents/generations/tasks',
    model: 'demo-video-model',
    taskId: 'task-42',
    elapsedMs: 1800,
    videoConfig: {
      prompt: 'A sunset',
      hasImage: false,
      uploadMode: 'url',
      hasLastFrame: false,
    },
    videoChecks: [{ id: 'video_submit', title: 'Task submit', status: 'pass' }],
    t: (key) => key,
  }

  const pdfHtml = buildVideoHtmlReport(input, { format: 'pdf' })
  const exportHtml = buildVideoHtmlReport(input)

  expect(pdfHtml).toContain(
    '<title>Doubao Video Generation Test Report</title>'
  )
  expect(pdfHtml).toContain('demo-video-model')
  expect(pdfHtml).toContain('task-42')
  expect(pdfHtml).toContain('class="document-letterhead"')
  expect(pdfHtml).toContain('<table class="pdf-shell"><thead>')
  expect(pdfHtml).toContain('margin:33pt 40pt 58pt')
  expect(pdfHtml).toContain('content:counter(page, decimal-leading-zero)')
  expect(pdfHtml).toContain('Example Operator Ltd')
  expect(pdfHtml).toContain(
    '<div class="document-operator"><img src="/api/pdf-branding/operating-logo" alt="Example Operator Ltd"/></div>'
  )
  expect(pdfHtml).not.toContain('<span>Example Operator Ltd</span>')
  expect(pdfHtml).not.toContain('192.0.2.44')
  expect(pdfHtml).not.toContain('meta-label">Time')
  expect(exportHtml).toContain('http://192.0.2.44')
})
